### ISSUE TITLE
'TypeError: Cannot read property '1' of null' when loading Reporter

### ISSUE THREAD

**Issue by zolrath** [electrode-io/electrode-webpack-reporter#4]
While testing electrode I've found that I don't actually get any errors output in my terminal:
```
content is served from C:\Users\furd\Desktop\electrode-test
webpack bundle is now VALID but has ERRORS
webpack report is served from http://localhost:2992/reporter
```

And if I try to go to `http://localhost:2992/reporter` to examine the errors there I am greeted with an blank page and this error in the terminal:
```
TypeError: Cannot read property '1' of null
    at ModuleProcessor._splitPathName (C:\Users\furd\Desktop\electrode-test\node_modules\electrode-webpack-reporter\lib\module-processor.js:55:18)
    at Object.keys.forEach (C:\Users\furd\Desktop\electrode-test\node_modules\electrode-webpack-reporter\lib\module-processor.js:83:26)
    at Array.forEach (native)
    at ModuleProcessor.makeModulesByPackage (C:\Users\furd\Desktop\electrode-test\node_modules\electrode-webpack-reporter\lib\module-processor.js:82:37)
    at Object.getModulesByPkg (C:\Users\furd\Desktop\electrode-test\node_modules\electrode-webpack-reporter\lib\stats-utils.js:33:29)
    at Object.res.format.json (C:\Users\furd\Desktop\electrode-test\node_modules\electrode-webpack-reporter\lib\webpack-reporter.js:78:34)
    at ServerResponse.res.format (C:\Users\furd\Desktop\electrode-test\node_modules\express\lib\response.js:628:13)
    at WebpackReporter._webReport (C:\Users\furd\Desktop\electrode-test\node_modules\electrode-webpack-reporter\lib\webpack-reporter.js:71:9)
    at Layer.handle [as handle_request] (C:\Users\furd\Desktop\electrode-test\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\furd\Desktop\electrode-test\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\furd\Desktop\electrode-test\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\furd\Desktop\electrode-test\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\furd\Desktop\electrode-test\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\furd\Desktop\electrode-test\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\furd\Desktop\electrode-test\node_modules\express\lib\router\index.js:271:10)
    at expressInit (C:\Users\furd\Desktop\electrode-test\node_modules\express\lib\middleware\init.js:33:5)
```

This is using a freshly generated electrode project on Windows 10, simply causing an error to occur such as removing a closing tag to the `<h2>` in `home.jsx`

**Comment by jchip** [comment]
Thanks for reporting the issue.  I develop on Linux where this is actually working.  I will see what I can do to get a Windows 10 machine to try this out.

**Comment by jchip** [comment]
what's your node and npm version?  I'd like to see if I can get the same issue using the same versions as you.

**Comment by zolrath** [comment]
node: v6.4.0
npm: 3.10.3

**Comment by spearmootz** [comment]
This also happens to me

Windows 7
node: 6.3.1
npm: 3.10.9

**Comment by adaniliuk-edmunds** [comment]
The same issue here 
Windows 10
node: 6.9.1
npm: 3.10.8

**Comment by jchip** [comment]
Hi all, thanks for reporting your settings.  I should be able to setup windows 10 in the next few days to fix this.  Do you use any Unix layer like cygwin on your setup or is it just plain windows 10 and cmd?

**Comment by spearmootz** [comment]
I used regular cmd.

**Comment by Eric013** [comment]
Hello,

I have same issues on mac os (el capitan 10.11.3):
node: v7.0.0
npm: 3.7.5

On: https://github.com/electrode-io/electrode-webpack-reporter/blob/master/lib/module-processor.js#L55
=> match is null because parameter name is "multi main"

On: https://github.com/electrode-io/electrode-webpack-reporter/blob/master/lib/module-processor.js#L82
=> this.modulesByName :
`{ 'multi main': 
   { id: 0,
     identifier: 'multi main',
     name: 'multi main',
     index: 0,
     index2: 712,
     size: 76,
     cacheable: true,
     built: true,
     optional: false,
     prefetched: false,
     chunks: [ 0 ],
     assets: [],
     issuer: null,
     profile: undefined,
     failed: false,
     errors: 0,
     warnings: 0 },
  '(webpack)-dev-server/client?http://localhost:2992': 
   { id: 1,
     identifier: '/Users/ericsanchez/Projects/projects-node/electrode-boilerplate/node_modules/webpack-dev-server/client/index.js?http://localhost:2992',
     name: '(webpack)-dev-server/client?http://localhost:2992',
     index: 1,
     index2: 72,
     size: 3974,
     cacheable: true,
     built: true,
     optional: false,
     prefetched: false,
     chunks: [ 0 ],
     assets: [],
     issuer: 'multi main',
     profile: undefined,
     failed: false,
     errors: 0,
     warnings: 0 },
  './~/url/url.js': 
   ...`

I hope help you :)
Thanks

**Comment by jchip** [comment]
@Eric013 thanks for the report.  I can make the match more robust.  It'd also help me if you could give me the details on how you generated the `multi main` module.

**Comment by Eric013** [comment]
@jchip i don't known which is **multi main** but i have same issue (same "multi main") on my linux debian.

**Comment by Craga89** [comment]
I've also got this issue. Debugging, it seems as if any module that is "ignored" causes the problem i.e. logging out `name` in [`_SplitPathName`](https://github.com/electrode-io/electrode-webpack-reporter/blob/master/lib/module-processor.js#L47) yields this:

``` js
jsdom (ignored)
```

**Comment by Craga89** [comment]
Adding the following line in [module-preprocessor.js#L90](https://github.com/electrode-io/electrode-webpack-reporter/blob/master/lib/module-processor.js#L90) seems to fix my issue

``` js
      if (name.indexOf('(ignored)') > -1) {
        return;
      }

```
